defmodule Dash.Repo.Migrations.AddOrgAndTeamTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :organization_id, :uuid, null: false
    end

    create table(:team_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role, :text, null: false, default: "member"

      add :team_id,
          references(:teams,
            column: :id,
            name: "team_members_team_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "team_members_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:team_members, [:team_id],
             name: "team_members_one_owner_per_team",
             unique: true,
             where: "role = 'owner'"
           )

    create unique_index(:team_members, [:team_id, :user_id],
             name: "team_members_unique_team_user_index"
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:teams) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "teams_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:teams, [:organization_id, :slug],
             name: "teams_unique_slug_per_org_index"
           )

    alter table(:organizations) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :slug, :text, null: false
      add :active, :boolean, null: false, default: true
      add :deactivated_at, :utc_datetime_usec
    end

    create unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:org_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role, :text, null: false, default: "member"

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "org_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "org_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:org_memberships, [:organization_id],
             name: "org_memberships_one_owner_per_org",
             unique: true,
             where: "role = 'owner'"
           )

    create unique_index(:org_memberships, [:user_id, :organization_id],
             name: "org_memberships_unique_user_per_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:org_memberships, [:user_id, :organization_id],
                     name: "org_memberships_unique_user_per_org_index"
                   )

    drop constraint(:org_memberships, "org_memberships_organization_id_fkey")

    drop constraint(:org_memberships, "org_memberships_user_id_fkey")

    drop_if_exists index(:org_memberships, [:organization_id],
                     name: "org_memberships_one_owner_per_org"
                   )

    drop table(:org_memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop_if_exists unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    alter table(:organizations) do
      remove :deactivated_at
      remove :active
      remove :slug
      remove :name
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists unique_index(:teams, [:organization_id, :slug],
                     name: "teams_unique_slug_per_org_index"
                   )

    drop constraint(:teams, "teams_organization_id_fkey")

    alter table(:teams) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop_if_exists unique_index(:team_members, [:team_id, :user_id],
                     name: "team_members_unique_team_user_index"
                   )

    drop constraint(:team_members, "team_members_team_id_fkey")

    drop constraint(:team_members, "team_members_user_id_fkey")

    drop_if_exists index(:team_members, [:team_id], name: "team_members_one_owner_per_team")

    drop table(:team_members)

    drop table(:teams)

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
    end
  end
end
