defmodule Dash.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pipeline_execution_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :duration_ms, :bigint
      add :records_fetched, :bigint, default: 0
      add :records_stored, :bigint, default: 0
      add :source_response_time_ms, :bigint
      add :error_type, :text
      add :error_message, :text
      add :error_details, :map
      add :metadata, :map, default: %{}

      add :pipeline_id,
          references(:pipelines,
            column: :id,
            name: "pipeline_execution_logs_pipeline_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:data_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :source_field, :text, null: false
      add :target_field, :text, null: false
      add :transformation_type, :text, default: "direct"
      add :required, :boolean, null: false, default: false

      add :pipeline_id,
          references(:pipelines,
            column: :id,
            name: "data_mappings_pipeline_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:data_mappings, [:pipeline_id, :target_field],
             name: "data_mappings_unique_target_per_pipeline_index"
           )
  end

  def down do
    drop_if_exists unique_index(:data_mappings, [:pipeline_id, :target_field],
                     name: "data_mappings_unique_target_per_pipeline_index"
                   )

    drop constraint(:data_mappings, "data_mappings_pipeline_id_fkey")

    drop table(:data_mappings)

    drop constraint(:pipeline_execution_logs, "pipeline_execution_logs_pipeline_id_fkey")

    drop table(:pipeline_execution_logs)
  end
end
