defmodule Dash.Repo.Migrations.Dashboards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:widgets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :type, :text, null: false
      add :config, :map, null: false, default: %{}
      add :position, :map, null: false
      add :dashboard_id, :uuid, null: false
      add :pipeline_id, :uuid, null: false
    end

    create table(:dashboards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:widgets) do
      modify :dashboard_id,
             references(:dashboards,
               column: :id,
               name: "widgets_dashboard_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :pipeline_id,
             references(:pipelines,
               column: :id,
               name: "widgets_pipeline_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:dashboards) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :description, :text
      add :is_default, :boolean, null: false, default: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "dashboards_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "dashboards_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:dashboards, [:organization_id, :name],
             name: "dashboards_unique_name_per_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:dashboards, [:organization_id, :name],
                     name: "dashboards_unique_name_per_org_index"
                   )

    drop constraint(:dashboards, "dashboards_organization_id_fkey")

    drop constraint(:dashboards, "dashboards_created_by_id_fkey")

    alter table(:dashboards) do
      remove :created_by_id
      remove :organization_id
      remove :is_default
      remove :description
      remove :name
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:widgets, "widgets_dashboard_id_fkey")

    drop constraint(:widgets, "widgets_pipeline_id_fkey")

    alter table(:widgets) do
      modify :pipeline_id, :uuid
      modify :dashboard_id, :uuid
    end

    drop table(:dashboards)

    drop table(:widgets)
  end
end
